export default function TermsPage() {
  return (
    <main style={mainStyle}>
      <section style={cardStyle}>
        <h1>Terms and Conditions</h1>

        <p><strong>Last updated:</strong> May 2026</p>

        <h2>1. Introduction</h2>
        <p>
          Welcome to QAForge AI. By using this website and tool, you agree to these Terms and Conditions.
          If you do not agree, please do not use the service.
        </p>

        <h2>2. Service Description</h2>
        <p>
          QAForge AI provides AI-assisted generation of QA test cases, API test cases, and automation-related outputs.
          The tool is designed to support QA workflows and reduce manual effort.
        </p>

        <h2>3. AI-Generated Output</h2>
        <p>
          The outputs generated by QAForge AI are created using artificial intelligence and may not always be complete,
          accurate, or suitable for every project. Users are responsible for reviewing, validating, and modifying all
          generated content before using it in real software testing or production workflows.
        </p>

        <h2>4. User Responsibility</h2>
        <p>
          Users must not use QAForge AI for illegal, harmful, abusive, or misleading purposes. Users are responsible
          for the information they enter into the tool and for how they use the generated output.
        </p>

        <h2>5. Sensitive Information</h2>
        <p>
          Do not enter sensitive, confidential, personal, financial, medical, or proprietary information into the tool.
          QAForge AI is intended for general QA assistance and test design support.
        </p>

        <h2>6. Account and Access</h2>
        <p>
          Some features may require sign-in. We may limit, suspend, or restrict access if the service is misused or abused.
        </p>

        <h2>7. Payments and Pro Features</h2>
        <p>
          Paid features may be introduced through a Pro plan. Pricing, limits, and available features may change over time.
          Any paid subscription terms will be shown clearly at the time of purchase.
        </p>

        <h2>8. No Warranty</h2>
        <p>
          QAForge AI is provided on an “as is” and “as available” basis. We do not guarantee that the service will always
          be error-free, uninterrupted, or fully accurate.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          QAForge AI is not liable for any loss, damage, missed defects, project issues, or business impact resulting from
          the use of AI-generated outputs. Users should always apply professional QA judgment.
        </p>

        <h2>10. Changes to Terms</h2>
        <p>
          We may update these Terms and Conditions from time to time. Continued use of the service means you accept the
          updated terms.
        </p>

        <h2>11. Contact</h2>
        <p>
          For questions, contact us at: <strong>printfluent.shop@gmail.com</strong>
        </p>

        <a href="/" style={backLink}>← Back to QAForge AI</a>
      </section>
    </main>
  );
}

const mainStyle = {
  minHeight: "100vh",
  background: "linear-gradient(135deg, #020617, #0f172a)",
  color: "#0f172a",
  padding: "40px 20px",
  fontFamily: "Arial, sans-serif",
};

const cardStyle = {
  maxWidth: "900px",
  margin: "0 auto",
  background: "#ffffff",
  borderRadius: "20px",
  padding: "32px",
  lineHeight: "1.7",
};

const backLink = {
  display: "inline-block",
  marginTop: "24px",
  color: "#2563eb",
  fontWeight: "bold",
  textDecoration: "none",
};